spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/weixin?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
    jap:
    show-sql: true

