spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Hejie_123
    url: jdbc:mysql://39.108.110.21:3306/weixin?useUnicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
    jap:
    show-sql: true

